KS-5-4 task accomplished
utka0047/KotlinSprintLessons pull request #28
Opened 2024-11-30 11:59 UTC by utka0047

2024-12-04 17:43 UTC, ievetrovdev requested changes

2024-12-04 17:43 UTC, ievetrovdev commented on src/main/kotlin/Lesson5/lesson5-task4.kt
> +    val userPassword = "PanGalactic"
Повнимательнее к ТЗ, пароль запрашивается, только если имя пользователя введено правильно

2024-12-04 18:05 UTC, utka0047 commented on src/main/kotlin/Lesson5/lesson5-task4.kt
> +    val userPassword = "PanGalactic"
честно говоря, это сообщение сложно назвать ТЗ

2024-12-05 18:26 UTC, ievetrovdev approved these changes

2024-12-05 20:01 UTC, merged